version: '3'
services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
      cache_from:
        - ${IMAGE_NAME}:${IMAGE_TAG}
    privileged: true
    ports:
        - "50001:50001"
