# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: role.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrole.proto\x12\x08protobuf\" \n\x04Role\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1c\n\x0eGetRoleRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"/\n\x0fGetRoleResponse\x12\x1c\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x0e.protobuf.Role2K\n\x0bRoleService\x12<\n\x03Get\x12\x18.protobuf.GetRoleRequest\x1a\x19.protobuf.GetRoleResponse\"\x00\x42\x0cZ\n./protobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'role_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n./protobuf'
  _ROLE._serialized_start=24
  _ROLE._serialized_end=56
  _GETROLEREQUEST._serialized_start=58
  _GETROLEREQUEST._serialized_end=86
  _GETROLERESPONSE._serialized_start=88
  _GETROLERESPONSE._serialized_end=135
  _ROLESERVICE._serialized_start=137
  _ROLESERVICE._serialized_end=212
# @@protoc_insertion_point(module_scope)
